# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

env:
  - CODECOV_TOKEN="4b64dbde-7d8e-483b-99b1-17a1adc7c2f4"

before_install:
  - sudo apt-get install -y libudunits2-dev libproj-dev libgeos++-dev libgdal-dev libv8-dev

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
